#194 - company phone and e-mail
blumilksoftware/website pull request #202
Opened 2023-08-04 12:02 UTC by kamilpiech97

Added company phone and e-mail on company info page.

Preview:
![image](https://github.com/blumilksoftware/website/assets/29115024/54d9a3e3-03d2-4e74-9d9c-86f92f2f053a)

Before merge we must update data for real data.

2023-08-04 12:36 UTC, krzysztofrewak requested changes

2023-08-04 12:36 UTC, krzysztofrewak commented on src/assets/contact.js
> +  email: 'biuro@blumilk.pl',
```suggestion
  email: 'office@blumilk.pl',
```

2023-08-04 12:36 UTC, krzysztofrewak commented on src/assets/contact.js
> +  phone: '+48 123 456 789',
```suggestion
  phone: '+48 579 710 703',
```

2023-08-05 06:29 UTC, krzysztofrewak approved these changes

2023-08-09 09:35 UTC, EwelinaLasowy approved these changes

2023-08-09 10:52 UTC, merged