- show references, cleanup
blumilksoftware/website pull request #266
Opened 2024-06-20 11:34 UTC by AleksandraKozubal

2024-06-24 08:41 UTC, EwelinaSkrzypacz reviewed
1. When no references are published, I see error

![image](https://github.com/blumilksoftware/website/assets/56546832/ef845cc7-5954-4aa4-93e9-bbbc7f91d4d7)

2. When there is two references, something strange is happen

https://github.com/blumilksoftware/website/assets/56546832/9d796bce-d54f-4245-a01f-7475f62e9a20

3. And on mobile we will always show one reference? Also, I see error in console, but I think it is because I don't have any image in storage/factory called reference.jpg

![image](https://github.com/blumilksoftware/website/assets/56546832/858b0fb1-5b12-4910-a04f-5b595e8043b0)

4. Why I can't click "Czytaj więcej"?

5. When I write too long name of reference author, I see error:

![image](https://github.com/blumilksoftware/website/assets/56546832/05deb6bc-dc46-4464-9d75-3b9be653150e)

2024-06-24 10:59 UTC, kamilpiech97 requested changes

2024-06-24 10:59 UTC, kamilpiech97 commented on resources/views/home.blade.php
> +//dd(count($references));
:eyes:

2024-06-24 10:59 UTC, kamilpiech97 commented on resources/views/home.blade.php
> +        <section class=" @if(count($references)==0) hidden @endif px-[10%] md:px-[15%] text-center items-center sm:pb-36 relative">
https://laravel.com/docs/11.x/blade#conditional-classes

2024-06-24 11:00 UTC, AleksandraKozubal commented
>     1. When no references are published, I see error
> 
>     2. When there is two references, something strange is happen
>
>     3. And on mobile we will always show one reference? Also, I see error in console, but I think it is because I don't have any image in storage/factory called reference.jpg
> 
>     4. Why I can't click "Czytaj więcej"?
> 
>     5. When I write too long name of reference author, I see error:


1,2. fixed
3. Yes, that was designed this way. Added those files, should be ok now
4. I didn't do it because of current design changes - designer is not sure if it will be still there, so it's better to wait and make it when needed
5. fixed

2024-06-24 12:05 UTC, AleksandraKozubal commented on resources/views/home.blade.php
> +//dd(count($references));
oops, deleted:D

2024-06-24 12:05 UTC, AleksandraKozubal commented on resources/views/home.blade.php
> +        <section class=" @if(count($references)==0) hidden @endif px-[10%] md:px-[15%] text-center items-center sm:pb-36 relative">
changed

2024-06-24 12:19 UTC, EwelinaSkrzypacz approved these changes

2024-06-24 12:21 UTC, kamilpiech97 requested changes

2024-06-24 12:21 UTC, kamilpiech97 commented on resources/views/home.blade.php
> +    $caseStudy = App::currentLocale()=='en' ? json_decode(file_get_contents(public_path('main_case_study.json')), true)['en'] : json_decode(file_get_contents(public_path('main_case_study.json')), tru
:eyes:

2024-06-24 12:26 UTC, kamilpiech97 requested changes

2024-06-24 12:26 UTC, kamilpiech97 commented on resources/views/home.blade.php
> +        <section @class([ 'hidden' => count($references)==0, 'px-[10%] md:px-[15%] text-center items-center sm:pb-36 relative' ])>
```suggestion
        <section @class([ 'hidden' => $references->isEmpty(), 'px-[10%] md:px-[15%] text-center items-center sm:pb-36 relative' ])>
```

2024-06-24 12:26 UTC, kamilpiech97 commented on resources/views/home.blade.php
> +            <div @class([ 'sm:block main-gallery js-flickity' => count($references)>3, 'sm:flex justify-center' => count($references)<=3])
```suggestion
            <div @class([ 'sm:block main-gallery js-flickity' => $references->->count() > 3, 'sm:flex justify-center' =>  $references->->count() <= 3])
```

2024-06-24 12:26 UTC, kamilpiech97 commented on resources/views/home.blade.php
> +            <div @class([ 'sm:block main-gallery js-flickity' => count($references)>3, 'sm:flex justify-center' => count($references)<=3])
For me, better should be moved that into variable in controller like `$referencesCount` and use them here

2024-06-25 04:34 UTC, kamilpiech97 requested changes

2024-06-25 04:34 UTC, kamilpiech97 commented on app/Http/Controllers/HomeController.php
> +        $locale = App::currentLocale();
```suggestion
        $locale = $request->getLocale();
```
instead of Facade usage

2024-06-25 04:34 UTC, kamilpiech97 commented on app/Http/Controllers/HomeController.php
> +        $caseStudy = $locale === "en" ? json_decode(file_get_contents(public_path("main_case_study.json")), true)["en"] : json_decode(file_get_contents(public_path("main_case_study.json")), true)["pl
```suggestion
        $caseStudy = json_decode(file_get_contents(public_path("main_case_study.json")), true)[$locale];
```
hm?

2024-06-25 04:34 UTC, kamilpiech97 commented on app/Http/Controllers/HomeController.php
> +        $referencesCount = count($references);
```suggestion
        $referencesCount = $references->count();
```

2024-06-25 04:35 UTC, kamilpiech97 commented on resources/views/home.blade.php
> +            <div @class([ 'sm:block main-gallery js-flickity' => $referencesCount>3, 'sm:flex justify-center' => $referencesCount<=3])
```suggestion
            <div @class([ 'sm:block main-gallery js-flickity' => $referencesCount > 3, 'sm:flex justify-center' => $referencesCount <= 3])
```

2024-06-25 06:21 UTC, kamilpiech97 commented on app/Http/Controllers/HomeController.php
> +    public function __invoke(Factory $factory, Request $request): View
```suggestion
    public function __invoke(Request $request, Factory $factory): View
```

2024-06-25 06:36 UTC, kamilpiech97 approved these changes

2024-06-25 06:36 UTC, EwelinaSkrzypacz approved these changes

2024-06-25 06:37 UTC, merged