- amendments
blumilksoftware/website pull request #353
Opened 2024-09-21 15:37 UTC by AleksandraKozubal

Amendments from our designer.

2024-09-23 05:49 UTC, EwelinaSkrzypacz approved these changes

2024-09-23 05:52 UTC, krzysztofrewak requested changes

2024-09-23 05:52 UTC, krzysztofrewak commented on lang/pl/content.php
> +                "subtitle" => "Należymy do grona założycieli prawdopodobnie największej grupy badawczej w obszarze sztucznej inteligencji w Polsce - SoDA AI Research Group Udzielamy eksperckich komen
```suggestion
                "subtitle" => "Należymy do grona założycieli prawdopodobnie największej grupy badawczej w obszarze sztucznej inteligencji w Polsce - SoDA AI Research Group. Udzielamy eksperckich komentarzy do raportów branżowych oraz prasy ogólnopolskiej, w tym Forbes i&nbsp;Dziennik Prawny. Szkolimy sektor publiczny ze sposobów wykorzystywania AI. Udzielamy eksperckich wywiadów w&nbsp;telewizji i radiu oraz występujemy na konferencjach.",
```

2024-09-23 05:52 UTC, krzysztofrewak commented on lang/pl/content.php
> +                "subtitle" => "Prowadzimy zajęcia na kierunku Informatyka i Inżynieria Produkcji i Logistyki w Collegium Witelona Uczelnia Państwowa w Legnicy. Organizujemy także otwarty program prak
```suggestion
                "subtitle" => "Prowadzimy zajęcia na kierunkach Informatyka i Inżynieria Produkcji i Logistyki w Collegium Witelona Uczelnia Państwowa w Legnicy. Organizujemy także otwarty program praktyk dla studentów kierunków informatycznych oraz jesteśmy partnerami w&nbsp;naukowych konferencjach.",
```

2024-09-23 05:52 UTC, krzysztofrewak commented on lang/pl/content.php
> +                "subtitle" => "Zajmujemy się różnorodnymi zagadnieniami badawczymi, obejmującymi: przetwarzanie dużych zbiorów danych (big data), rozwiązywanie problemów szeregowania zadań, wykorzyst
```suggestion
                "subtitle" => "Zajmujemy się różnorodnymi zagadnieniami badawczymi, obejmującymi przetwarzanie dużych zbiorów danych (big data), rozwiązywanie problemów szeregowania zadań, wykorzystywanie sztucznej inteligencji, optymalizację. Dzięki doświadczeniu i&nbsp;wiedzy zdobytej przez członków naszego zespołu, jesteśmy w&nbsp;stanie skutecznie zarządzać i realizować projekty R&D, zapewniając naszym Klientom najwyższą jakość i innowacyjność w każdym etapie współpracy.",
```

2024-09-25 10:44 UTC, EwelinaSkrzypacz approved these changes

2024-09-25 10:46 UTC, krzysztofrewak approved these changes

2024-09-25 10:59 UTC, merged